services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: fluora_light_ha
    volumes:
      - ./config:/config
      - ./custom_components:/config/custom_components
    ports:
      - "8123:8123"
    environment:
      - TZ=UTC
    restart: unless-stopped
